### ISSUE TITLE
Cloud fraction change term

### ISSUE THREAD

**Issue by znicholls** [mzelinka/aprp#1]
Hi @mzelinka,

Thanks for this repository, super helpful (and for including a working example)!

I have what I hope is a quick question. Does your code calculate the last term of equation A2 of Zelinka et al. 2014 (the <a href="https://www.codecogs.com/eqnedit.php?latex=\Delta&space;C_{\mathrm{tot}}&space;[R_{\mathrm{ov}}&space;-&space;R_{\mathrm{clr}}]" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\Delta&space;C_{\mathrm{tot}}&space;[R_{\mathrm{ov}}&space;-&space;R_{\mathrm{clr}}]" title="\Delta C_{\mathrm{tot}} [R_{\mathrm{ov}} - R_{\mathrm{clr}}]" /></a> term)? Or is this not part of APRP hence not in there?

Cheers,

Zeb

**Comment by mzelinka** [comment]
Hi Zeb,

Sorry for my extreme delay in responding. That term is identical to the “cloud amount” component that is computed by APRP. Let me know if you have any other questions and I will hopefully respond quicker!

Mark

**Comment by znicholls** [comment]
Hi Mark,

Thanks for the reply! I'm asking because I'm thinking about implementing APRP in the [ESMValTool](https://github.com/ESMValGroup/ESMValTool) and want to make sure I've understood what it does before I do so. 

> That term is identical to the “cloud amount” component that is computed by APRP.

Just to make sure I've understood correctly, <a href="https://www.codecogs.com/eqnedit.php?latex=\Delta&space;C_{\mathrm{tot}}&space;[R_{\mathrm{ov}}&space;-&space;R_{\mathrm{clr}}]" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\Delta&space;C_{\mathrm{tot}}&space;[R_{\mathrm{ov}}&space;-&space;R_{\mathrm{clr}}]" title="\Delta C_{\mathrm{tot}} [R_{\mathrm{ov}} - R_{\mathrm{clr}}]" /></a> is identical to the third term of equation 16b) of [Taylor et al. 2017](https://journals.ametsoc.org/doi/pdf/10.1175/JCLI4143.1), i.e. what you calculate here https://github.com/mzelinka/aprp/blob/b403fa0999af9ac66e7df9896ef1decc2aedbcc0/code/python/demonstrate_APRP.py#L132?

**Comment by mzelinka** [comment]
My APRP code is written to follow exactly the equations in Taylor et al (2007). (Note the references to equation numbers from Taylor et al in the comments of the code.) The equations at the appendix of Zelinka et al (2014) are expressed in a slightly different form, which (I think) we did in an effort to more clearly explain the calculations in that paper. They should be identical to those in Taylor et al, just expressed differently. Let me know if you are having specific problems reconciling them.

**Comment by znicholls** [comment]
Ok great thanks. I’ll close this for now then and reopen if I have any more questions.

Thanks again!
